FROM python:3.10-slim-bookworm

WORKDIR /app

COPY requirements.txt requirements-dashboard.txt ./

RUN pip install --no-cache-dir -r requirements-dashboard.txt

COPY src/ ./src/
COPY sql/ ./sql/
COPY dashboard/ ./dashboard/

ENV PYTHONPATH=/app:$PYTHONPATH

CMD ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
